# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# encoding: utf-8









Type.create(:name => 'マンション')
Type.create(:name => 'アパート')
Type.create(:name => '土地')
Type.create(:name => '駐車場')
Type.create(:name => '空きスペース')
Type.create(:name => '倉庫')


Prefecture.create(:name => '北海道')
Prefecture.create(:name => '青森県')
Prefecture.create(:name => '岩手県')
Prefecture.create(:name => '宮城県')
Prefecture.create(:name => '秋田県')
Prefecture.create(:name => '山形県')
Prefecture.create(:name => '福島県')
Prefecture.create(:name => '茨城県')
Prefecture.create(:name => '栃木県')
Prefecture.create(:name => '群馬県')
Prefecture.create(:name => '埼玉県')
Prefecture.create(:name => '千葉県')
Prefecture.create(:name => '東京都')
Prefecture.create(:name => '神奈川県')
Prefecture.create(:name => '新潟県')
Prefecture.create(:name => '富山県')
Prefecture.create(:name => '石川県')
Prefecture.create(:name => '福井県')
Prefecture.create(:name => '山梨県')
Prefecture.create(:name => '長野県')
Prefecture.create(:name => '岐阜県')
Prefecture.create(:name => '静岡県')
Prefecture.create(:name => '愛知県')
Prefecture.create(:name => '三重県')
Prefecture.create(:name => '滋賀県')
Prefecture.create(:name => '京都府')
Prefecture.create(:name => '大阪府')
Prefecture.create(:name => '兵庫県')
Prefecture.create(:name => '奈良県')
Prefecture.create(:name => '和歌山県')
Prefecture.create(:name => '鳥取県')
Prefecture.create(:name => '島根県')
Prefecture.create(:name => '岡山県')
Prefecture.create(:name => '広島県')
Prefecture.create(:name => '山口県')
Prefecture.create(:name => '徳島県')
Prefecture.create(:name => '香川県')
Prefecture.create(:name => '愛媛県')
Prefecture.create(:name => '高知県')
Prefecture.create(:name => '福岡県')
Prefecture.create(:name => '佐賀県')
Prefecture.create(:name => '長崎県')
Prefecture.create(:name => '熊本県')
Prefecture.create(:name => '大分県')
Prefecture.create(:name => '宮崎県')
Prefecture.create(:name => '鹿児島県')
Prefecture.create(:name => '沖縄県')



City.create(:name => '千代田区', :prefecture_id => '13')
City.create(:name => '中央区', :prefecture_id => '13')
City.create(:name => '港区', :prefecture_id => '13')
City.create(:name => '新宿区', :prefecture_id => '13')
City.create(:name => '文京区', :prefecture_id => '13')
City.create(:name => '台東区', :prefecture_id => '13')
City.create(:name => '墨田区', :prefecture_id => '13')
City.create(:name => '江東区', :prefecture_id => '13')
City.create(:name => '品川区', :prefecture_id => '13')
City.create(:name => '目黒区', :prefecture_id => '13')
City.create(:name => '大田区', :prefecture_id => '13')
City.create(:name => '世田谷区', :prefecture_id => '13')
City.create(:name => '渋谷区', :prefecture_id => '13')
City.create(:name => '中野区', :prefecture_id => '13')
City.create(:name => '杉並区', :prefecture_id => '13')
City.create(:name => '豊島区', :prefecture_id => '13')
City.create(:name => '北区', :prefecture_id => '13')
City.create(:name => '荒川区', :prefecture_id => '13')
City.create(:name => '板橋区', :prefecture_id => '13')
City.create(:name => '練馬区', :prefecture_id => '13')
City.create(:name => '足立区', :prefecture_id => '13')
City.create(:name => '葛飾区', :prefecture_id => '13')
City.create(:name => '江戸川区', :prefecture_id => '13')
City.create(:name => '八王子市', :prefecture_id => '13')
City.create(:name => '立川市', :prefecture_id => '13')
City.create(:name => '武蔵野市', :prefecture_id => '13')
City.create(:name => '三鷹市', :prefecture_id => '13')
City.create(:name => '青梅市', :prefecture_id => '13')
City.create(:name => '府中市', :prefecture_id => '13')
City.create(:name => '昭島市', :prefecture_id => '13')
City.create(:name => '調布市', :prefecture_id => '13')
City.create(:name => '町田市', :prefecture_id => '13')
City.create(:name => '小金井市', :prefecture_id => '13')
City.create(:name => '小平市', :prefecture_id => '13')
City.create(:name => '日野市', :prefecture_id => '13')
City.create(:name => '東村山市', :prefecture_id => '13')
City.create(:name => '国分寺市', :prefecture_id => '13')
City.create(:name => '国立氏', :prefecture_id => '13')
City.create(:name => '福生市', :prefecture_id => '13')
City.create(:name => '狛江市', :prefecture_id => '13')
City.create(:name => '東大和市', :prefecture_id => '13')
City.create(:name => '清瀬市', :prefecture_id => '13')
City.create(:name => '東久留米市', :prefecture_id => '13')
City.create(:name => '武蔵村山市', :prefecture_id => '13')
City.create(:name => '多摩市', :prefecture_id => '13')
City.create(:name => '稲城市', :prefecture_id => '13')
City.create(:name => '羽村市', :prefecture_id => '13')
City.create(:name => 'あきる野市', :prefecture_id => '13')
City.create(:name => '西東京市', :prefecture_id => '13')
City.create(:name => '西多摩郡瑞穂町', :prefecture_id => '13')
City.create(:name => '西多摩郡日の出町', :prefecture_id => '13')
City.create(:name => '西多摩郡檜原村', :prefecture_id => '13')
City.create(:name => '西多摩郡奥多摩町', :prefecture_id => '13')
City.create(:name => '大島町', :prefecture_id => '13')
City.create(:name => '利島村', :prefecture_id => '13')
City.create(:name => '新島村', :prefecture_id => '13')
City.create(:name => '神津島村', :prefecture_id => '13')
City.create(:name => '三宅島三宅村', :prefecture_id => '13')
City.create(:name => '御蔵島村', :prefecture_id => '13')
City.create(:name => '八丈島八丈町', :prefecture_id => '13')
City.create(:name => '青ヶ島村', :prefecture_id => '13')
City.create(:name => '小笠原村', :prefecture_id => '13')







